import { test } from 'node:test';
import assert from 'node:assert/strict';
import { fetchCnQuoteWithFallback, fetchCnQuotesBatchWithFallback } from '../workers/markets/src/marketRuntime.js';
import { isValidQuoteCacheSource } from '../workers/markets/src/quoteCache.js';

function line() { const f = Array(69).fill(''); f[0]='51'; f[1]='NASDAQ100ETF'; f[2]='159659'; f[3]='2.321'; f[4]='2.345'; f[5]='2.319'; f[6]='256563'; f[31]='-0.024'; f[32]='-1.02'; f[33]='2.326'; f[34]='2.317'; f[37]='59570751'; f[45]='106.2'; f[67]='2.477'; f[68]='1.767'; return `v_sz159659="${f.join('~')}";`; }
function mock({ navOk=true, calls=[] }={}) { return async (input) => { const url=String(input); calls.push(url); if (url.includes('stock.xueqiu.com/v5/stock/quote.json')) return new Response('bad',{status:400}); if (url.includes('qt.gtimg.cn')) return new Response(line(),{status:200}); if (url.includes('push2delay.eastmoney.com')) return Response.json({data:{diff:[]}}); if (url.includes('fundmobapi.eastmoney.com')) return navOk ? Response.json({Datas:[{FCODE:'159659',NAV:'2.2',HQDATE:'2026-09-10'}]}) : new Response('bad',{status:400}); if (url.includes('/api/notify/admin/alert')) return new Response('',{status:204}); throw new Error(`unexpected ${url}`); }; }

test('Tencent fallback calculates premiumPercent from latest NAV', async () => { const original=globalThis.fetch; const calls=[]; globalThis.fetch=mock({calls}); try { const out=await fetchCnQuotesBatchWithFallback({XUEQIU_COOKIE:'x'},[{raw:'159659',code:'sz159659'}]); const q=out['159659']; assert.equal(calls.some((url) => url.includes('danjuanapp.com')),false); assert.equal(q.source,'tencent-quote'); assert.equal(q.price,2.321); assert.equal(q.latestNav,2.2); assert.equal(q.premiumEngine,'collector'); assert.equal(q.premiumPercent,5.5); assert.equal(q.premiumSource,'nav'); assert.match(q.primaryError,/HTTP 400/); } finally { globalThis.fetch=original; } });
test('Tencent fallback keeps premiumPercent null when NAV fails', async () => { const original=globalThis.fetch; globalThis.fetch=mock({navOk:false}); try { const q=await fetchCnQuoteWithFallback({XUEQIU_COOKIE:'x'},'sz159659'); assert.equal(q.source,'tencent-quote'); assert.equal(Object.hasOwn(q,'premiumPercent'),true); assert.equal(q.premiumPercent,null); assert.equal(q.premiumSource,null); } finally { globalThis.fetch=original; } });
test('CN cache accepts enriched Tencent quote and rejects price-only legacy fallback', () => { assert.equal(isValidQuoteCacheSource({source:'tencent-quote',price:2.321,navBase:2.2,premiumPercent:5.5},'cn'),true); assert.equal(isValidQuoteCacheSource({source:'tencent-quote',price:2.321},'cn'),false); });
