import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  loadSwitchConfigFromWorker,
  loadSwitchSnapshotFromWorker,
  normalizeSwitchConfigShape,
  readSwitchConfigCache,
  saveSwitchConfigToWorker
} from '../../app/switchStrategySync.js';
import { testSwitchConfig } from '../../app/switchStrategyTestSync.js';
import { SWITCH_STRATEGY_ETFS } from '../../app/nasdaqCatalog.js';
import { readLedgerState } from '../../app/holdingsLedger.js';
import { aggregateByCode } from '../../app/holdingsLedgerCore.js';
import { buildSwitchBoardRows, filterSwitchBoardRows, summarizeSwitchBoard } from './switchBoardModel.js';
import { readSwitchRuleChannelMap } from './switchRuleChannels.js';
import { SwitchStrategyMetricsBar } from './SwitchStrategyMetricsBar.jsx';
import { SwitchStrategyCardItem } from './SwitchStrategyCardItem.jsx';
import { SwitchStrategyTable } from './SwitchStrategyTable.jsx';
import { SwitchStrategyRuleModal } from './SwitchStrategyRuleModal.jsx';

const AUTO_HIGH_CODES = new Set(['159501', '513100']);
const AUTO_LOWER_PCT = 1;
const AUTO_UPPER_PCT = 3;

function isFundCode(value) {
  return /^\d{6}$/.test(String(value || '').trim());
}

function uniqueCodes(values = []) {
  return Array.from(new Set(values.map((value) => String(value || '').trim()).filter(isFundCode)));
}

function buildRuleFromPayload(payload, existingRule = null, ruleId = '') {
  const highCodes = uniqueCodes(Array.isArray(payload.highCodes) ? payload.highCodes : [payload.highCode]);
  const lowCodes = uniqueCodes(Array.isArray(payload.lowCodes) ? payload.lowCodes : [payload.lowCode])
    .filter((code) => !highCodes.includes(code));
  const allCodes = [...highCodes, ...lowCodes];
  const holdingSide = ['H', 'L', 'BOTH'].includes(payload.holdingSide) ? payload.holdingSide : 'H';
  const benchmarkCodes = holdingSide === 'L' ? lowCodes : holdingSide === 'BOTH' ? allCodes : highCodes;
  return {
    ...(existingRule || {}),
    id: ruleId,
    name: payload.name,
    enabled: existingRule ? Boolean(existingRule.enabled) : true,
    benchmarkCodes,
    enabledCodes: allCodes,
    premiumClass: Object.fromEntries([
      ...highCodes.map((code) => [code, 'H']),
      ...lowCodes.map((code) => [code, 'L'])
    ]),
    intraSellLowerPct: payload.lowerPct,
    intraBuyOtherPct: payload.upperPct,
    ...(payload.autoGenerated ? {
      holdingFundCode: payload.holdingFundCode,
      holdingFundName: payload.holdingFundName,
      holdingQuantity: payload.holdingQuantity,
      holdingNotional: payload.holdingNotional,
      candidateFundCodes: payload.candidateFundCodes,
      feeConfig: payload.feeConfig,
      backtestTimeframe: payload.backtestTimeframe || '5m'
    } : {})
  };
}

function mergeSwitchSnapshot(current, payload) {
  const previousRoot = current?.snapshot && typeof current.snapshot === 'object'
    ? current.snapshot
    : (current && typeof current === 'object' ? current : {});
  const incomingRoot = payload?.snapshot && typeof payload.snapshot === 'object'
    ? payload.snapshot
    : (payload && typeof payload === 'object' ? payload : null);
  if (!incomingRoot) return current;
  const incomingRules = Array.isArray(incomingRoot.rules) ? incomingRoot.rules : [];
  const incomingIds = new Set(incomingRules.map((entry) => String(entry?.ruleId || entry?.id || entry?.snapshot?.ruleId || '')).filter(Boolean));
  const previousRules = Array.isArray(previousRoot.rules) ? previousRoot.rules : [];
  return {
    snapshot: {
      ...previousRoot,
      ...incomingRoot,
      rules: [
        ...previousRules.filter((entry) => !incomingIds.has(String(entry?.ruleId || entry?.id || entry?.snapshot?.ruleId || ''))),
        ...incomingRules
      ]
    }
  };
}

function hasFiniteValue(value) {
  return value != null && value !== '' && Number.isFinite(Number(value));
}

function snapshotHasRulePremium(snapshot, ruleId) {
  const root = snapshot?.snapshot || snapshot;
  const entry = (Array.isArray(root?.rules) ? root.rules : []).find((item) => (
    String(item?.ruleId || item?.id || item?.snapshot?.ruleId || '') === String(ruleId || '')
  ));
  const value = entry?.snapshot || entry;
  return (Array.isArray(value?.byBenchmark) ? value.byBenchmark : []).some((group) => (
    hasFiniteValue(group?.benchmarkPremiumPct)
      || (Array.isArray(group?.candidates) && group.candidates.some((item) => hasFiniteValue(item?.premiumPct)))
  ));
}

function readHoldingForAutoFill(code) {
  try {
    const ledger = readLedgerState();
    const item = aggregateByCode(ledger.transactions || [], ledger.snapshotsByCode || {})
      .find((holding) => String(holding?.code || '').replace(/^(sh|sz|bj)/i, '') === code);
    const marketValue = Number(item?.marketValue);
    const quantity = Number(item?.totalShares || item?.movingTotalShares);
    if (item && Number.isFinite(marketValue) && marketValue > 0) {
      return {
        name: String(item.name || ''),
        notional: marketValue,
        quantity: Number.isFinite(quantity) && quantity > 0 ? quantity : null,
        usedDefaultNotional: false
      };
    }
  } catch (_error) {
    // 持仓读取失败时使用约定的默认金额，自动填充仍可继续。
  }
  return {
    name: '',
    notional: 10_000,
    quantity: null,
    usedDefaultNotional: true
  };
}


export function SwitchStrategyBoardExperience({ onOpenBacktest, onOpenQuickTrade } = {}) {
  const [config, setConfig] = useState(() => normalizeSwitchConfigShape(readSwitchConfigCache()));
  const [snapshot, setSnapshot] = useState(null);
  const [keyword, setKeyword] = useState('');
  const [viewMode, setViewMode] = useState('grid');
  const [modalOpen, setModalOpen] = useState(false);
  const [editingRuleId, setEditingRuleId] = useState('');
  const [channelMap, setChannelMap] = useState(() => readSwitchRuleChannelMap());
  const [busyRuleId, setBusyRuleId] = useState('');
  const [testingRuleId, setTestingRuleId] = useState('');

  useEffect(() => {
    Promise.all([
      loadSwitchConfigFromWorker().catch(() => null),
      loadSwitchSnapshotFromWorker().catch(() => null)
    ]).then(([nextConfig, nextSnapshot]) => {
      if (nextConfig) setConfig(nextConfig);
      if (nextSnapshot) setSnapshot(nextSnapshot);
      const activeRule = (nextConfig?.rules || []).find((rule) => rule.id === nextConfig?.activeRuleId)
        || (nextConfig?.rules || []).find((rule) => rule.enabled);
      if (activeRule && !snapshotHasRulePremium(nextSnapshot, activeRule.id)) {
        testSwitchConfig({
          ...nextConfig,
          enabled: true,
          activeRuleId: activeRule.id,
          rules: [{ ...activeRule, enabled: true }]
        }).then((payload) => {
          setSnapshot((current) => mergeSwitchSnapshot(current || nextSnapshot, payload));
        }).catch(() => {});
      }
    });
  }, []);

  const rules = useMemo(
    () => (config.rules || []).filter((rule) => (rule.benchmarkCodes || []).length || (rule.enabledCodes || []).length),
    [config]
  );
  const rows = useMemo(() => buildSwitchBoardRows({ rules }, snapshot, { channelsByRuleId: channelMap }), [rules, snapshot, channelMap]);

  const visibleRows = useMemo(() => filterSwitchBoardRows(rows, keyword), [rows, keyword]);
  const summary = useMemo(() => summarizeSwitchBoard(rows), [rows]);
  const monitoring = useMemo(() => rows.filter((r) => r.enabled).length, [rows]);
  const editingRow = useMemo(() => rows.find((row) => row.id === editingRuleId) || null, [rows, editingRuleId]);

  // 处理方案保存（新建 / 编辑），配置结构与 Worker 的多基准模型保持一致。
  const handleSaveRule = useCallback(async (payload) => {
    const isNew = !payload.ruleId;
    const ruleId = isNew ? `rule-${Date.now().toString(36)}` : payload.ruleId;
    const existingRule = (config.rules || []).find((rule) => rule.id === payload.ruleId) || null;
    const nextRule = buildRuleFromPayload(payload, existingRule, ruleId);
    const nextRules = isNew
      ? [...(config.rules || []), nextRule]
      : (config.rules || []).map((rule) => (rule.id === ruleId ? nextRule : rule));
    const nextConfig = normalizeSwitchConfigShape({
      ...config,
      enabled: true,
      activeRuleId: ruleId,
      rules: nextRules
    });

    setConfig(nextConfig);
    setModalOpen(false);
    setBusyRuleId(ruleId);
    try {
      await saveSwitchConfigToWorker(nextConfig);
      const savedRule = (nextConfig.rules || []).find((rule) => rule.id === ruleId);
      if (savedRule) {
        const payloadResult = await testSwitchConfig({
          ...nextConfig,
          enabled: true,
          activeRuleId: ruleId,
          rules: [{ ...savedRule, enabled: true }]
        });
        setSnapshot((current) => mergeSwitchSnapshot(current, payloadResult));
      }
    } catch (error) {
      console.warn('Worker sync error:', error);
    } finally {
      setBusyRuleId('');
    }
  }, [config]);

  // 仅测试当前规则，保留多 H / 多 L 配置，并用返回快照更新看板。
  const handleTestRule = useCallback(async (row) => {
    const sourceRule = row.rule || {};
    const rule = {
      ...sourceRule,
      id: row.id,
      name: row.name,
      enabled: true
    };
    setTestingRuleId(row.id);
    try {
      const payload = await testSwitchConfig({
        ...config,
        enabled: false,
        activeRuleId: rule.id,
        rules: [rule]
      });
      setSnapshot((current) => mergeSwitchSnapshot(current, payload));
    } catch (error) {
      console.warn('testSwitchConfig feedback trigger:', error);
    } finally {
      setTestingRuleId('');
    }
  }, [config]);

  const handleToggleRule = useCallback(async (row) => {
    const nextConfig = normalizeSwitchConfigShape({
      ...config,
      rules: (config.rules || []).map((rule) => rule.id === row.id ? { ...rule, enabled: !rule.enabled } : rule)
    });
    setConfig(nextConfig);
    setBusyRuleId(row.id);
    try {
      await saveSwitchConfigToWorker(nextConfig);
    } catch (error) {
      console.warn('Worker sync error:', error);
    } finally {
      setBusyRuleId('');
    }
  }, [config]);

  const handleDeleteRule = useCallback(async (row) => {
    if (typeof window !== 'undefined' && !window.confirm(`确定删除“${row.name}”吗？删除后将同步到云端。`)) return;
    const nextRules = (config.rules || []).filter((rule) => rule.id !== row.id);
    const nextConfig = normalizeSwitchConfigShape({
      ...config,
      activeRuleId: config.activeRuleId === row.id ? (nextRules[0]?.id || '') : config.activeRuleId,
      rules: nextRules
    });
    setConfig(nextConfig);
    setBusyRuleId(row.id);
    try {
      await saveSwitchConfigToWorker(nextConfig);
    } catch (error) {
      console.warn('Worker sync error:', error);
    } finally {
      setBusyRuleId('');
    }
  }, [config]);

  // 复用旧版 Beta 的云端候选分析流程，为新建弹窗生成 H/L 双腿和阈值。
  const handleAutoFillRule = useCallback(async ({ holdingCode, feeWanRate }) => {
    const normalizedHoldingCode = String(holdingCode || '').trim();
    if (!isFundCode(normalizedHoldingCode)) throw new Error('请填写 6 位当前持仓代码。');
    const normalizedFeeWanRate = Number(feeWanRate);
    if (!Number.isFinite(normalizedFeeWanRate) || normalizedFeeWanRate < 0) {
      throw new Error('请填写有效的万分之交易费率。');
    }
    const holding = readHoldingForAutoFill(normalizedHoldingCode);
    const commissionRatePct = normalizedFeeWanRate / 100;
    const estimatedTotalFee = Number(
      (holding.notional * normalizedFeeWanRate / 10_000 * 2).toFixed(2)
    );

    const candidates = Array.from(new Set([
      ...SWITCH_STRATEGY_ETFS.map((item) => item.code),
      ...AUTO_HIGH_CODES
    ]))
      .filter((code) => isFundCode(code) && code !== normalizedHoldingCode)
      .slice(0, 20);
    const codes = [normalizedHoldingCode, ...candidates];
    const premiumClass = Object.fromEntries(
      codes.map((code) => [code, AUTO_HIGH_CODES.has(code) ? 'H' : 'L'])
    );
    const holdingClass = premiumClass[normalizedHoldingCode];
    const previewRule = {
      id: 'recommend-preview',
      name: `${normalizedHoldingCode} 切换方案`,
      enabled: true,
      benchmarkCodes: [normalizedHoldingCode],
      enabledCodes: codes,
      premiumClass,
      intraSellLowerPct: AUTO_LOWER_PCT,
      intraBuyOtherPct: AUTO_UPPER_PCT,
      holdingFundCode: normalizedHoldingCode,
      holdingFundName: holding.name,
      holdingQuantity: holding.quantity,
      holdingNotional: holding.notional,
      candidateFundCodes: candidates,
      feeConfig: {
        mode: 'detailed',
        sellCommissionRate: commissionRatePct,
        buyCommissionRate: commissionRatePct,
        minimumCommission: 0,
        otherFee: 0,
        estimatedTotalFee
      },
      backtestTimeframe: '5m'
    };

    const api = await testSwitchConfig({
      enabled: true,
      activeRuleId: previewRule.id,
      rules: [previewRule]
    });
    const preview = api?.snapshot?.rules?.[0]?.snapshot;
    const group = (preview?.byBenchmark || []).find(
      (item) => String(item?.benchmarkCode || '') === normalizedHoldingCode
    ) || preview?.byBenchmark?.[0];
    const choices = (group?.candidates || [])
      .filter((item) => (
        item?.valid
        && premiumClass[item.code]
        && premiumClass[item.code] !== holdingClass
        && Number.isFinite(Number(item.spreadVsBenchmarkPct))
      ))
      .map((item) => ({
        ...item,
        normalizedGap: holdingClass === 'H'
          ? Number(item.spreadVsBenchmarkPct)
          : -Number(item.spreadVsBenchmarkPct)
      }))
      .sort((a, b) => (
        holdingClass === 'H'
          ? b.normalizedGap - a.normalizedGap
          : a.normalizedGap - b.normalizedGap
      ));
    const candidate = choices[0];
    if (!candidate) throw new Error('云端暂未返回可用的反向候选基金，请稍后重试。');

    const highCode = holdingClass === 'H' ? normalizedHoldingCode : candidate.code;
    const lowCode = holdingClass === 'L' ? normalizedHoldingCode : candidate.code;
    return {
      name: `${normalizedHoldingCode} 切换方案`,
      highCode,
      lowCode,
      lowerPct: Number(preview?.intraSellLowerPct ?? AUTO_LOWER_PCT),
      upperPct: Number(preview?.intraBuyOtherPct ?? AUTO_UPPER_PCT),
      holdingSide: holdingClass,
      holdingFundCode: normalizedHoldingCode,
      holdingFundName: String(holding.name || group?.benchmarkName || normalizedHoldingCode),
      holdingQuantity: holding.quantity,
      holdingNotional: holding.notional,
      candidateFundCodes: [candidate.code],
      feeConfig: previewRule.feeConfig,
      backtestTimeframe: previewRule.backtestTimeframe,
      message: `已匹配 ${candidate.code} ${candidate.name || ''}。按${holding.usedDefaultNotional ? '默认' : '当前'}持仓金额 ${holding.notional.toLocaleString('zh-CN')} 元、万${normalizedFeeWanRate}估算单次切换费用 ${estimatedTotalFee.toLocaleString('zh-CN')} 元。`
    };
  }, []);

  return (
    <div className="space-y-3 sm:space-y-4">
      {/* 统计概览与操作栏 */}
      <SwitchStrategyMetricsBar
        total={rows.length}
        monitoring={monitoring}
        triggeredToday={summary.triggeredToday}
        keyword={keyword}
        onKeywordChange={setKeyword}
        viewMode={viewMode}
        onViewModeChange={setViewMode}
        onCreate={() => { setEditingRuleId(''); setModalOpen(true); }}
      />

      {/* 方案卡片列表 */}
      {viewMode === 'grid' ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3 sm:gap-4">
          {visibleRows.map((row) => (
            <SwitchStrategyCardItem
              key={row.id}
              row={row}
              busy={busyRuleId === row.id}
              testing={testingRuleId === row.id}
              onToggle={() => handleToggleRule(row)}
              onEdit={() => { setEditingRuleId(row.id); setModalOpen(true); }}
              onTest={() => handleTestRule(row)}
              onDelete={() => handleDeleteRule(row)}
            />
          ))}
        </div>
      ) : (
        <SwitchStrategyTable
          rows={visibleRows}
          busyRuleId={busyRuleId}
          testingRuleId={testingRuleId}
          onEdit={(row) => { setEditingRuleId(row.id); setModalOpen(true); }}
          onToggle={(row) => handleToggleRule(row)}
          onTest={(row) => handleTestRule(row)}
          onDelete={(row) => handleDeleteRule(row)}
        />
      )}

      {/* 规则弹窗 */}
      <SwitchStrategyRuleModal
        open={modalOpen}
        row={editingRow}
        initialRule={editingRow}
        onClose={() => setModalOpen(false)}
        onAutoFill={handleAutoFillRule}
        onSave={handleSaveRule}
      />
    </div>
  );
}

export default SwitchStrategyBoardExperience;
