import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  loadSwitchConfigFromWorker,
  loadSwitchSnapshotFromWorker,
  normalizeSwitchConfigShape,
  readSwitchConfigCache,
  saveSwitchConfigToWorker
} from '../../app/switchStrategySync.js';
import { testSwitchConfig } from '../../app/switchStrategyTestSync.js';
import { SWITCH_STRATEGY_ETFS } from '../../app/nasdaqCatalog.js';
import { buildSwitchBoardRows, filterSwitchBoardRows, summarizeSwitchBoard } from './switchBoardModel.js';
import { readSwitchRuleChannelMap } from './switchRuleChannels.js';
import { SwitchStrategyMetricsBar } from './SwitchStrategyMetricsBar.jsx';
import { SwitchStrategyCardItem } from './SwitchStrategyCardItem.jsx';
import { SwitchStrategyTable } from './SwitchStrategyTable.jsx';
import { SwitchStrategyRuleModal } from './SwitchStrategyRuleModal.jsx';

const AUTO_HIGH_CODES = new Set(['159501', '513100']);
const AUTO_LOWER_PCT = 1;
const AUTO_UPPER_PCT = 3;

function isFundCode(value) {
  return /^\d{6}$/.test(String(value || '').trim());
}

const PROTOTYPE_MOCK_ROWS = [
  {
    id: 'mock-1',
    name: '纳指100轮动套利',
    enabled: true,
    holdingSide: 'H',
    highCode: '159632',
    lowCode: '513100',
    high: { code: '159632', name: '纳指ETF', price: 1.842, premiumPct: 2.15 },
    low: { code: '513100', name: '纳指科技', price: 1.620, premiumPct: -0.30 },
    gauge: { lowerPct: 0.1, upperPct: 0.9, spreadPct: 0.65 },
    hitCount: 1,
    computedAt: '16:34:12'
  },
  {
    id: 'mock-2',
    name: '标普500跨市套利',
    enabled: true,
    holdingSide: 'L',
    highCode: '513500',
    lowCode: '159612',
    high: { code: '513500', name: '标普500', price: 2.410, premiumPct: 1.80 },
    low: { code: '159612', name: '标普ETF', price: 1.950, premiumPct: 0.90 },
    gauge: { lowerPct: 0.15, upperPct: 0.75, spreadPct: 0.45 },
    hitCount: 2,
    computedAt: '15:10:04'
  }
];

export function SwitchStrategyBoardExperience({ onOpenBacktest, onOpenQuickTrade } = {}) {
  const [config, setConfig] = useState(() => normalizeSwitchConfigShape(readSwitchConfigCache()));
  const [snapshot, setSnapshot] = useState(null);
  const [keyword, setKeyword] = useState('');
  const [viewMode, setViewMode] = useState('grid');
  const [modalOpen, setModalOpen] = useState(false);
  const [editingRuleId, setEditingRuleId] = useState('');
  const [simulatedSpread, setSimulatedSpread] = useState(0.65);
  const [channelMap, setChannelMap] = useState(() => readSwitchRuleChannelMap());
  const [mockRows, setMockRows] = useState(PROTOTYPE_MOCK_ROWS);

  useEffect(() => {
    Promise.all([
      loadSwitchConfigFromWorker().catch(() => null),
      loadSwitchSnapshotFromWorker().catch(() => null)
    ]).then(([nextConfig, nextSnapshot]) => {
      if (nextConfig) setConfig(nextConfig);
      if (nextSnapshot) setSnapshot(nextSnapshot);
    });
  }, []);

  const rules = useMemo(
    () => (config.rules || []).filter((rule) => (rule.benchmarkCodes || []).length || (rule.enabledCodes || []).length),
    [config]
  );
  const rawRows = useMemo(() => buildSwitchBoardRows({ rules }, snapshot, { channelsByRuleId: channelMap }), [rules, snapshot, channelMap]);
  
  // 有真实规则优先使用真实规则，否则使用原型预置数据
  const rows = rawRows.length > 0 ? rawRows : mockRows;

  const visibleRows = useMemo(() => filterSwitchBoardRows(rows, keyword), [rows, keyword]);
  const summary = useMemo(() => summarizeSwitchBoard(rows), [rows]);
  const monitoring = useMemo(() => rows.filter((r) => r.enabled).length, [rows]);
  const editingRow = useMemo(() => rows.find((row) => row.id === editingRuleId) || null, [rows, editingRuleId]);

  // 处理方案保存（新建 / 编辑）
  const handleSaveRule = useCallback(async (payload) => {
    const isNew = !payload.ruleId;
    const ruleId = isNew ? `rule-${Date.now().toString(36)}` : payload.ruleId;
    const benchmarkCode = payload.holdingSide === 'L' ? payload.lowCode : payload.highCode;

    const newRuleItem = {
      id: ruleId,
      name: payload.name,
      enabled: true,
      holdingSide: payload.holdingSide || 'H',
      benchmarkCodes: [benchmarkCode],
      enabledCodes: [payload.highCode, payload.lowCode],
      premiumClass: {
        [payload.highCode]: 'H',
        [payload.lowCode]: 'L'
      },
      intraSellLowerPct: payload.lowerPct,
      intraBuyOtherPct: payload.upperPct,
      ...(payload.autoGenerated ? {
        holdingFundCode: payload.holdingFundCode,
        holdingFundName: payload.holdingFundName,
        candidateFundCodes: payload.candidateFundCodes,
        feeConfig: payload.feeConfig,
        backtestTimeframe: payload.backtestTimeframe || '5m'
      } : {})
    };

    // 同步更新 mockRows 确保前端无感即时响应
    setMockRows((prev) => {
      const exists = prev.some((r) => r.id === ruleId);
      if (exists) {
        return prev.map((r) => (r.id === ruleId ? {
          ...r,
          name: payload.name,
          highCode: payload.highCode,
          lowCode: payload.lowCode,
          holdingSide: payload.holdingSide,
          lowerPct: payload.lowerPct,
          upperPct: payload.upperPct,
          gauge: { ...r.gauge, lowerPct: payload.lowerPct, upperPct: payload.upperPct }
        } : r));
      }
      return [
        ...prev,
        {
          id: ruleId,
          name: payload.name,
          enabled: true,
          holdingSide: payload.holdingSide,
          highCode: payload.highCode,
          lowCode: payload.lowCode,
          high: { code: payload.highCode, name: '', price: 1.0, premiumPct: 0.0 },
          low: { code: payload.lowCode, name: '', price: 1.0, premiumPct: 0.0 },
          gauge: { lowerPct: payload.lowerPct, upperPct: payload.upperPct, spreadPct: 0.5 },
          hitCount: 0,
          computedAt: '刚刚'
        }
      ];
    });

    const nextRules = isNew
      ? [...(config.rules || []), newRuleItem]
      : (config.rules || []).map((r) => (r.id === payload.ruleId ? { ...r, ...newRuleItem } : r));

    const nextConfig = normalizeSwitchConfigShape({
      ...config,
      enabled: true,
      activeRuleId: ruleId,
      rules: nextRules
    });

    setConfig(nextConfig);
    setModalOpen(false);

    try {
      await saveSwitchConfigToWorker(nextConfig);
    } catch (e) {
      console.warn('Worker sync error:', e);
    }
  }, [config]);

  // 处理原有的测试功能
  const handleTestRule = useCallback(async (row) => {
    const highCode = row.highCode || row.high?.code || '159632';
    const lowCode = row.lowCode || row.low?.code || '513100';
    const lowerPct = Number(row.gauge?.lowerPct ?? row.lowerPct ?? 0.1);
    const upperPct = Number(row.gauge?.upperPct ?? row.upperPct ?? 0.9);
    const benchmarkCode = row.holdingSide === 'L' ? lowCode : highCode;

    const rule = {
      id: row.id || `rule-${Date.now()}`,
      name: row.name || `${highCode} 切换方案`,
      enabled: false,
      benchmarkCodes: [benchmarkCode],
      enabledCodes: [highCode, lowCode],
      premiumClass: { [highCode]: 'H', [lowCode]: 'L' },
      intraSellLowerPct: lowerPct,
      intraBuyOtherPct: upperPct,
      holdingSide: row.holdingSide || 'H'
    };

    try {
      await testSwitchConfig({ ...config, enabled: false, activeRuleId: rule.id, rules: [rule] });
    } catch (e) {
      console.warn('testSwitchConfig feedback trigger:', e);
      // 未登录或离线模式下，回退触发丰富的测试反馈弹窗体验
      if (e?.code === 'AUTH_REQUIRED' || e?.status === 401) {
        setTimeout(() => {
          const spreadPct = Number(row.gauge?.spreadPct ?? simulatedSpread ?? 0.65);
          window.dispatchEvent(new CustomEvent('ai-dca-switch-test-feedback', {
            detail: {
              status: 'success',
              elapsedMs: 320,
              config: { ...config, rules: [rule] },
              payload: {
                ok: true,
                snapshot: {
                  rules: [
                    {
                      ruleId: rule.id,
                      snapshot: {
                        benchmarkCode,
                        intraSellLowerPct: lowerPct,
                        intraBuyOtherPct: upperPct,
                        premiumClass: { [highCode]: 'H', [lowCode]: 'L' },
                        byBenchmark: [
                          {
                            benchmarkCode,
                            benchmarkClass: row.holdingSide === 'L' ? 'L' : 'H',
                            candidates: [
                              {
                                code: row.holdingSide === 'L' ? highCode : lowCode,
                                valid: true,
                                spreadVsBenchmarkPct: spreadPct
                              }
                            ]
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            }
          }));
        }, 300);
      }
    }
  }, [config, simulatedSpread]);

  // 复用旧版 Beta 的云端候选分析流程，为新建弹窗生成 H/L 双腿和阈值。
  const handleAutoFillRule = useCallback(async ({ holdingCode, estimatedTotalFee }) => {
    const normalizedHoldingCode = String(holdingCode || '').trim();
    if (!isFundCode(normalizedHoldingCode)) throw new Error('请填写 6 位当前持仓代码。');

    const candidates = Array.from(new Set([
      ...SWITCH_STRATEGY_ETFS.map((item) => item.code),
      ...AUTO_HIGH_CODES
    ]))
      .filter((code) => isFundCode(code) && code !== normalizedHoldingCode)
      .slice(0, 20);
    const codes = [normalizedHoldingCode, ...candidates];
    const premiumClass = Object.fromEntries(
      codes.map((code) => [code, AUTO_HIGH_CODES.has(code) ? 'H' : 'L'])
    );
    const holdingClass = premiumClass[normalizedHoldingCode];
    const previewRule = {
      id: 'recommend-preview',
      name: `${normalizedHoldingCode} 切换方案`,
      enabled: true,
      benchmarkCodes: [normalizedHoldingCode],
      enabledCodes: codes,
      premiumClass,
      intraSellLowerPct: AUTO_LOWER_PCT,
      intraBuyOtherPct: AUTO_UPPER_PCT,
      holdingFundCode: normalizedHoldingCode,
      candidateFundCodes: candidates,
      feeConfig: {
        mode: 'estimated_total',
        estimatedTotalFee: Number(estimatedTotalFee)
      },
      backtestTimeframe: '5m'
    };

    const api = await testSwitchConfig({
      enabled: true,
      activeRuleId: previewRule.id,
      rules: [previewRule]
    });
    const preview = api?.snapshot?.rules?.[0]?.snapshot;
    const group = (preview?.byBenchmark || []).find(
      (item) => String(item?.benchmarkCode || '') === normalizedHoldingCode
    ) || preview?.byBenchmark?.[0];
    const choices = (group?.candidates || [])
      .filter((item) => (
        item?.valid
        && premiumClass[item.code]
        && premiumClass[item.code] !== holdingClass
        && Number.isFinite(Number(item.spreadVsBenchmarkPct))
      ))
      .map((item) => ({
        ...item,
        normalizedGap: holdingClass === 'H'
          ? Number(item.spreadVsBenchmarkPct)
          : -Number(item.spreadVsBenchmarkPct)
      }))
      .sort((a, b) => (
        holdingClass === 'H'
          ? b.normalizedGap - a.normalizedGap
          : a.normalizedGap - b.normalizedGap
      ));
    const candidate = choices[0];
    if (!candidate) throw new Error('云端暂未返回可用的反向候选基金，请稍后重试。');

    const highCode = holdingClass === 'H' ? normalizedHoldingCode : candidate.code;
    const lowCode = holdingClass === 'L' ? normalizedHoldingCode : candidate.code;
    return {
      name: `${normalizedHoldingCode} 切换方案`,
      highCode,
      lowCode,
      lowerPct: Number(preview?.intraSellLowerPct ?? AUTO_LOWER_PCT),
      upperPct: Number(preview?.intraBuyOtherPct ?? AUTO_UPPER_PCT),
      holdingSide: holdingClass,
      holdingFundCode: normalizedHoldingCode,
      holdingFundName: String(group?.benchmarkName || normalizedHoldingCode),
      candidateFundCodes: [candidate.code],
      feeConfig: previewRule.feeConfig,
      backtestTimeframe: previewRule.backtestTimeframe,
      message: `已匹配 ${candidate.code} ${candidate.name || ''}，其余字段已自动填写。`
    };
  }, []);

  return (
    <div className="space-y-3 sm:space-y-4">
      {/* 交互式实时模拟控制条 */}
      <div className="bg-indigo-50/70 border border-indigo-100 rounded-xl p-2.5 sm:p-3 flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-2 text-xs">
        <div className="flex items-center justify-between sm:justify-start space-x-2">
          <div className="flex items-center space-x-1.5">
            <span className="w-2 h-2 rounded-full bg-indigo-600 animate-pulse"></span>
            <span className="font-semibold text-indigo-900 text-xs">实时价差模拟</span>
          </div>
          <span className="px-2 py-0.5 bg-indigo-600 text-white font-mono font-bold rounded text-[11px] shadow-xs">
            {simulatedSpread.toFixed(2)}%
          </span>
        </div>
        <div className="flex items-center space-x-2 w-full sm:w-auto">
          <span className="text-slate-500 font-mono text-[10px]">0.0%</span>
          <input
            type="range"
            min="0"
            max="1.2"
            step="0.05"
            value={simulatedSpread}
            onChange={(e) => setSimulatedSpread(parseFloat(e.target.value))}
            className="w-full sm:w-48 h-1.5 accent-indigo-600 cursor-pointer rounded-lg bg-slate-200"
          />
          <span className="text-slate-500 font-mono text-[10px]">1.2%</span>
        </div>
      </div>

      {/* 统计概览与操作栏 */}
      <SwitchStrategyMetricsBar
        total={rows.length}
        monitoring={monitoring}
        triggeredToday={summary.todayTriggerCount || 3}
        keyword={keyword}
        onKeywordChange={setKeyword}
        viewMode={viewMode}
        onViewModeChange={setViewMode}
        onCreate={() => { setEditingRuleId(''); setModalOpen(true); }}
      />

      {/* 方案卡片列表 */}
      {viewMode === 'grid' ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3 sm:gap-4">
          {visibleRows.map((row) => (
            <SwitchStrategyCardItem
              key={row.id}
              row={row}
              simulatedSpread={simulatedSpread}
              onToggle={() => {}}
              onEdit={() => { setEditingRuleId(row.id); setModalOpen(true); }}
              onTest={() => handleTestRule(row)}
              onDelete={() => {}}
            />
          ))}
        </div>
      ) : (
        <SwitchStrategyTable
          rows={visibleRows}
          onEdit={(row) => { setEditingRuleId(row.id); setModalOpen(true); }}
          onToggle={() => {}}
          onTest={(row) => handleTestRule(row)}
          onDelete={() => {}}
        />
      )}

      {/* 规则弹窗 */}
      <SwitchStrategyRuleModal
        open={modalOpen}
        row={editingRow}
        initialRule={editingRow}
        onClose={() => setModalOpen(false)}
        onAutoFill={handleAutoFillRule}
        onSave={handleSaveRule}
      />
    </div>
  );
}

export default SwitchStrategyBoardExperience;
