import { Suspense, lazy, useEffect, useMemo, useState } from 'react';
import { BarChart3, History, LayoutGrid, Settings2, Sparkles } from 'lucide-react';
import { cx } from '../components/experience-ui.jsx';
import { trackFeatureEvent } from '../app/analytics.js';
import { triggerConversionPrompt } from '../app/conversionPrompts.js';
import { SwitchTestFeedbackModal } from '../components/fund-switch/SwitchTestFeedbackModal.jsx';

const SwitchStrategyBoardExperienceLazy = lazy(() => import('./switch/SwitchStrategyBoardExperience.jsx').then((m) => ({ default: m.SwitchStrategyBoardExperience })));
const SwitchStrategySetupExperienceLazy = lazy(() => import('./SwitchStrategySetupExperience.jsx').then((m) => ({ default: m.SwitchStrategySetupExperience })));
const SwitchStrategyBetaExperienceLazy = lazy(() => import('./SwitchStrategyBetaExperience.jsx').then((m) => ({ default: m.SwitchStrategyBetaExperience })));
const FundSwitchAnalysisExperienceLazy = lazy(() => import('./FundSwitchAnalysisExperience.jsx').then((m) => ({ default: m.FundSwitchAnalysisExperience })));
const BacktestExperienceLazy = lazy(() => import('./BacktestExperience.jsx').then((m) => ({ default: m.BacktestExperience })));
const STRATEGY_VARIANT_KEY = 'aiDcaSwitchStrategyUiVariant';
const STRATEGY_VARIANTS = ['board', 'classic', 'beta'];
const SUB_TABS = [
  { id: 'config', label: '方案配置', shortLabel: '方案', icon: Settings2 },
  { id: 'analysis', label: '策略复盘', shortLabel: '复盘', icon: History },
  { id: 'backtest', label: '策略回测', shortLabel: '回测', icon: BarChart3 }
];
const VARIANT_TOGGLES = [
  { id: 'board', label: '看板视图', shortLabel: '看板', icon: LayoutGrid },
  { id: 'classic', label: '标准版', shortLabel: '标准', icon: null },
  { id: 'beta', label: '创建向导', shortLabel: '向导', icon: Sparkles }
];
function readInitialView() { if (typeof window === 'undefined') return 'config'; const value = new URLSearchParams(window.location.search).get('view') || ''; return SUB_TABS.some((item) => item.id === value) ? value : 'config'; }
function readStrategyVariant() { if (typeof window === 'undefined') return 'board'; const stored = window.localStorage.getItem(STRATEGY_VARIANT_KEY) || ''; return STRATEGY_VARIANTS.includes(stored) ? stored : 'board'; }
function SubViewLoadingFallback() { return <div role="status" className="flex min-h-[40vh] items-center justify-center text-sm text-slate-400">加载中…</div>; }

export function FundSwitchExperience({ inPagesDir = false, embedded = false } = {}) {
  const [activeView, setActiveView] = useState(readInitialView);
  const [strategyVariant, setStrategyVariant] = useState(readStrategyVariant);
  const entryAttribution = useMemo(() => { if (typeof window === 'undefined') return {}; const params = new URLSearchParams(window.location.search || ''); return { entrySource: String(params.get('source') || '').slice(0, 60), fromNotification: params.get('source') === 'notification' }; }, []);
  useEffect(() => { trackFeatureEvent('fund_switch', 'view_open', { view: activeView, embedded, inPagesDir, strategyVariant, ...entryAttribution }); const timer = window.setTimeout(() => triggerConversionPrompt('fund_switch_view_open', { view: activeView }), 15000); return () => window.clearTimeout(timer); }, [activeView, embedded, entryAttribution, inPagesDir, strategyVariant]);
  function selectView(nextView) { if (nextView === activeView) return; const previousView = activeView; setActiveView(nextView); if (typeof window !== 'undefined') { const url = new URL(window.location.href); url.searchParams.set('tab', 'fundSwitch'); if (nextView === 'config') url.searchParams.delete('view'); else url.searchParams.set('view', nextView); if (nextView !== 'backtest') url.searchParams.delete('symbol'); window.history.replaceState({ tab: 'fundSwitch', view: nextView }, '', url); } trackFeatureEvent('fund_switch', 'subtab_select', { view: nextView, previousView, ...entryAttribution }); }
  function selectStrategyVariant(nextVariant) { setStrategyVariant(nextVariant); if (typeof window !== 'undefined') window.localStorage.setItem(STRATEGY_VARIANT_KEY, nextVariant); trackFeatureEvent('fund_switch', 'strategy_variant_select', { variant: nextVariant, ...entryAttribution }); }
  function openBacktest(code) { const symbol = String(code || '').trim(); setActiveView('backtest'); if (typeof window !== 'undefined') { const url = new URL(window.location.href); url.searchParams.set('tab', 'fundSwitch'); url.searchParams.set('view', 'backtest'); if (symbol) url.searchParams.set('symbol', symbol); else url.searchParams.delete('symbol'); window.history.replaceState({ tab: 'fundSwitch', view: 'backtest' }, '', url); } trackFeatureEvent('fund_switch', 'card_backtest_open', { symbol, ...entryAttribution }); }
  function openQuickTrade(code) { const symbol = String(code || '').trim(); trackFeatureEvent('fund_switch', 'card_quick_trade_open', { symbol, ...entryAttribution }); if (typeof window === 'undefined') return; const url = new URL(window.location.href); url.searchParams.set('tab', 'holdings'); url.searchParams.delete('view'); if (symbol) url.searchParams.set('code', symbol); else url.searchParams.delete('code'); window.location.assign(url.toString()); }
  return <div className={cx('mx-auto max-w-7xl space-y-4', embedded ? 'px-3 sm:px-6' : 'px-4 sm:px-6')}><div className="sticky top-0 z-20 flex items-center gap-1.5 rounded-2xl border border-slate-200/80 bg-white/95 p-1.5 shadow-sm backdrop-blur"><div className="min-w-0 flex-1 overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><div className="flex min-w-max gap-1 rounded-xl bg-slate-100 p-1 sm:min-w-full" role="tablist" aria-label="基金切换功能">{SUB_TABS.map((tab) => { const Icon = tab.icon; const active = activeView === tab.id; return <button key={tab.id} type="button" role="tab" aria-selected={active} onClick={() => selectView(tab.id)} className={cx('inline-flex min-h-11 shrink-0 items-center justify-center gap-1.5 whitespace-nowrap rounded-lg px-2.5 text-sm font-bold transition-all sm:flex-1 sm:px-2', active ? (tab.id === 'backtest' ? 'bg-indigo-50 text-indigo-700 ring-1 ring-indigo-100' : 'bg-white text-slate-950 shadow-sm ring-1 ring-slate-200/70') : 'text-slate-500 hover:text-slate-800')}><Icon className="h-4 w-4 shrink-0" /><span className="hidden sm:inline">{tab.label}</span><span className="sm:hidden">{tab.shortLabel}</span></button>; })}</div></div>{activeView === 'config' ? <div className="inline-flex shrink-0 rounded-xl border border-slate-200 bg-white p-1" aria-label="方案界面版本">{VARIANT_TOGGLES.map((item) => { const Icon = item.icon; const active = strategyVariant === item.id; return <button key={item.id} type="button" aria-pressed={active} onClick={() => selectStrategyVariant(item.id)} className={cx('inline-flex min-h-9 items-center gap-1 whitespace-nowrap rounded-lg px-2 text-[11px] font-bold sm:px-2.5 sm:text-xs', active ? (item.id === 'classic' ? 'bg-slate-100 text-slate-900' : 'bg-indigo-50 text-indigo-700') : 'text-slate-400')}>{Icon ? <Icon className="h-3.5 w-3.5" /> : null}<span className="sm:hidden">{item.shortLabel}</span><span className="hidden sm:inline">{item.label}</span></button>; })}</div> : null}</div><div role="tabpanel" aria-label={SUB_TABS.find((item) => item.id === activeView)?.label} className="min-w-0"><Suspense fallback={<SubViewLoadingFallback />}>{activeView === 'config' && strategyVariant === 'board' ? <SwitchStrategyBoardExperienceLazy onOpenBacktest={openBacktest} onOpenQuickTrade={openQuickTrade} /> : null}{activeView === 'config' && strategyVariant === 'classic' ? <SwitchStrategySetupExperienceLazy /> : null}{activeView === 'config' && strategyVariant === 'beta' ? <div className="[&>div>div:first-child>div:first-child]:hidden"><SwitchStrategyBetaExperienceLazy /></div> : null}{activeView === 'analysis' ? <FundSwitchAnalysisExperienceLazy /> : null}{activeView === 'backtest' ? <BacktestExperienceLazy embedded /> : null}</Suspense></div><SwitchTestFeedbackModal /></div>;
}
