name = "ai-dca-sync-test"
main = "src/index.js"
compatibility_date = "2026-03-30"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "test.freebacktrack.tech/api/sync/*"
zone_name = "freebacktrack.tech"

[[d1_databases]]
binding = "DB"
database_name = "ai-dca-sync-db"
database_id = "b0e5feab-dbcf-4ba7-9f3f-2e5169e8d868"

[[kv_namespaces]]
binding = "SYNC_BACKUPS"
id = "34af9b7435a84b5290e179875d272f27"

[placement]
mode = "smart"
