CREATE TABLE IF NOT EXISTS fund_periodic_reports (
  fund_code TEXT NOT NULL,
  art_code TEXT NOT NULL,
  report_type TEXT,
  report_period TEXT,
  report_date TEXT,
  publish_date TEXT,
  title TEXT,
  benchmark_name TEXT,
  fund_return_3m REAL,
  benchmark_return_3m REAL,
  tracking_difference_3m REAL,
  fund_volatility_3m REAL,
  benchmark_volatility_3m REAL,
  volatility_difference_3m REAL,
  fund_return_1y REAL,
  benchmark_return_1y REAL,
  tracking_difference_1y REAL,
  fund_volatility_1y REAL,
  benchmark_volatility_1y REAL,
  volatility_difference_1y REAL,
  daily_tracking_deviation_limit REAL,
  annual_tracking_error_limit REAL,
  tracking_error_actual REAL,
  source_url TEXT,
  source_title TEXT,
  parser_type TEXT,
  parser_status TEXT,
  extraction_model TEXT,
  extraction_confidence REAL,
  raw_json TEXT,
  fetched_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (fund_code, art_code)
);

CREATE INDEX IF NOT EXISTS idx_fund_reports_code_period
ON fund_periodic_reports(fund_code, report_period);
