import fs from 'node:fs/promises';

const FUND_CODE_SEARCH_URL = 'https://fund.eastmoney.com/js/fundcode_search.js';
const DATA_OUT = 'data/all_qdii.json';
const APP_CODES_OUT = 'src/app/qdiiFundCodes.js';
const MARKETS_CODES_OUT = 'workers/markets/src/qdiiFundCodes.js';
const WORKER_CODES_OUT = 'workers/notify/src/qdiiFundCodes.js';

function parseFundCodeSearch(text = '') {
  const match = String(text).match(/var\s+r\s*=\s*(\[[\s\S]*\]);?/);
  if (!match) throw new Error('fundcode_search.js format changed: missing var r array');
  const parsed = JSON.parse(match[1]);
  if (!Array.isArray(parsed)) throw new Error('fundcode_search.js format changed: r is not an array');
  return parsed;
}

function normalizeEntry(row) {
  const [code, pinyinAbbr, name, type, pinyin] = Array.isArray(row) ? row : [];
  const normalizedCode = String(code || '').trim();
  if (!/^\d{6}$/.test(normalizedCode)) return null;
  return {
    code: normalizedCode,
    name: String(name || '').trim(),
    type: String(type || '').trim(),
    pinyinAbbr: String(pinyinAbbr || '').trim(),
    pinyin: String(pinyin || '').trim()
  };
}

function isQdii(entry) {
  return /QDII|海外/i.test(`${entry.type} ${entry.name}`);
}

function buildCodeModule(funds, { includeNames = false } = {}) {
  const codes = funds.map((entry) => entry.code);
  const namesByCode = Object.fromEntries(funds.map((entry) => [entry.code, entry.name]));
  const lines = [
    '// Auto-generated by scripts/fetch_all_qdii.mjs. Do not edit by hand.',
    `export const QDII_FUND_CODES = new Set(${JSON.stringify(codes)});`,
    '',
    "export function isKnownQdiiFundCode(code = '') {",
    "  return QDII_FUND_CODES.has(String(code || '').trim());",
    '}',
    ''
  ];
  if (includeNames) {
    lines.splice(
      2,
      0,
      `export const QDII_FUND_NAMES_BY_CODE = ${JSON.stringify(namesByCode, null, 2)};`
    );
    lines.splice(
      lines.length - 1,
      0,
      '',
      "export function getKnownQdiiFundName(code = '') {",
      "  return QDII_FUND_NAMES_BY_CODE[String(code || '').trim()] || '';",
      '}'
    );
  }
  return lines.join('\n');
}

async function main() {
  const response = await fetch(FUND_CODE_SEARCH_URL, {
    headers: {
      accept: 'application/javascript,text/javascript,*/*',
      'user-agent': 'Mozilla/5.0'
    }
  });
  if (!response.ok) throw new Error(`fundcode_search.js HTTP ${response.status}`);
  const text = await response.text();
  const rows = parseFundCodeSearch(text).map(normalizeEntry).filter(Boolean);
  const qdii = rows.filter(isQdii).sort((a, b) => a.code.localeCompare(b.code));
  const codes = qdii.map((entry) => entry.code);
  const generatedAt = new Date().toISOString();
  const payload = {
    dataset: 'all_qdii',
    version: 1,
    generatedAt,
    source: FUND_CODE_SEARCH_URL,
    sourceNote: '天天基金 fundcode_search.js; entries whose type/name contains QDII or 海外.',
    count: qdii.length,
    codes,
    funds: qdii
  };

  await fs.writeFile(DATA_OUT, `${JSON.stringify(payload, null, 2)}\n`);
  await fs.writeFile(APP_CODES_OUT, buildCodeModule(qdii, { includeNames: true }));
  await fs.writeFile(MARKETS_CODES_OUT, buildCodeModule(qdii));
  await fs.writeFile(WORKER_CODES_OUT, buildCodeModule(qdii));
  console.log(JSON.stringify({ generatedAt, count: qdii.length, sample: qdii.slice(0, 5) }, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
