import React from 'react';
import { createRoot } from 'react-dom/client';
import { ScreenPage } from './pages/ScreenPage.jsx';
import { AppEntryAdGate } from './components/monetization.jsx';
import { RegionSwitchBanner } from './components/region-switch-banner.jsx';
import { initPostHog } from './app/posthog.js';
import { registerAssetCacheWhenIdle } from './app/assetCacheRegistration.js';
import { bootstrapRemoteStorage } from './app/remoteStorage.js';
import './styles/app.css';

function runWhenIdle(callback, { timeout = 2500, delayMs = 0 } = {}) { if (typeof window === 'undefined') return; const schedule = () => { if ('requestIdleCallback' in window) window.requestIdleCallback(callback, { timeout }); else window.setTimeout(callback, Math.min(timeout, 1200)); }; if (delayMs > 0) window.setTimeout(schedule, delayMs); else schedule(); }
function loadAdsScriptWhenIdle() { runWhenIdle(() => { if (document.querySelector('script[data-ai-dca-ads="adsense"]')) return; const script = document.createElement('script'); script.async = true; script.crossOrigin = 'anonymous'; script.dataset.aiDcaAds = 'adsense'; script.src = 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1376743188081698'; document.head.appendChild(script); }, { timeout: 4500, delayMs: 45000 }); }
function startPostHogWhenIdle() { runWhenIdle(() => { initPostHog(); }, { timeout: 3500, delayMs: 30000 }); }
function startNotifyRealtimeWhenIdle() { runWhenIdle(async () => { try { const [{ readNotifyAccountUsername, readNotifyClientConfig }, { startNotifyRealtime }] = await Promise.all([import('./app/notifySync.js'), import('./app/notifyWsClient.js')]); const config = readNotifyClientConfig(); if (!config?.notifyClientId || !config?.notifyClientSecret) return; const options = { clientId: config.notifyClientId, clientSecret: config.notifyClientSecret, clientLabel: config.notifyClientLabel, accountUsername: readNotifyAccountUsername(), debug: false, logLifecycle: true, onStatusChange: (status) => { window.__aiDcaNotifyWsStatus = status; window.dispatchEvent(new CustomEvent('ai-dca-notify-ws-status', { detail: { status } })); } }; const client = startNotifyRealtime(options); window.__aiDcaDisconnectNotifyWs = client.disconnect; } catch { /* notification is optional */ } }, { timeout: 2500, delayMs: 30000 }); }
function renderError(error) { createRoot(document.getElementById('root')).render(<main className="flex min-h-screen items-center justify-center bg-slate-50 p-6 text-slate-900"><section className="w-full max-w-md rounded-2xl border border-red-100 bg-white p-6 shadow-sm"><h1 className="text-lg font-bold">远端数据加载失败</h1><p className="mt-3 text-sm leading-6 text-slate-600">为了避免把失败误判为空账户，页面没有覆盖或清空本机数据。请检查网络后重试。</p><p className="mt-3 break-words rounded-xl bg-red-50 px-3 py-2 text-xs text-red-700">{error?.message || '远端数据服务暂时不可用'}</p><button type="button" className="mt-5 rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white" onClick={() => window.location.reload()}>重新加载</button></section></main>); }
function renderApp() { const inPagesDir = /\/pages(?:-v2)?\//.test(window.location.pathname); createRoot(document.getElementById('root')).render(<React.StrictMode><RegionSwitchBanner /><AppEntryAdGate><ScreenPage inPagesDir={inPagesDir} /></AppEntryAdGate></React.StrictMode>); startPostHogWhenIdle(); startNotifyRealtimeWhenIdle(); loadAdsScriptWhenIdle(); registerAssetCacheWhenIdle(runWhenIdle); }
void bootstrapRemoteStorage().then(renderApp).catch(renderError);
